
import { Category, Boat } from '@/types';

export const CATEGORIES: Category[] = [
    {
        id: 'cat-deluxe',
        slug: 'deluxe',
        title: 'Deluxe Collection',
        tagline: 'The Essential Backwater Experience',
        description: 'Perfect for first-time visitors offering comfortable amenities and authentic Kerala cuisine.',
        shortDescription: 'Comfortable air-conditioned bedrooms with classic wooden interiors.',
        guestCapacity: '2-6 Guests',
        amenities: [
            { icon: 'wind', title: 'AC Bedroom', description: '9PM - 6AM' },
            { icon: 'utensils', title: 'Full Board Meals', description: 'Traditional Kerala Cuisine' },
            { icon: 'wifi', title: 'Standard WiFi', description: 'Basic connectivity' },
        ],
        stats: {
            totalBoats: 6,
            rating: 4.5,
        },
        heroImage: '/packages/deluxe.webp',
        testimonials: [],
        whatsappTemplate: 'Hi, I am interested in the Deluxe Collection houseboats.',
    },
    {
        id: 'cat-premium',
        slug: 'premium',
        title: 'Premium Collection',
        tagline: 'Elevated Comfort & Style',
        description: 'Added luxuries including full-time AC and upgraded interiors for a superior stay.',
        shortDescription: 'Glass-walled living areas and anytime air-conditioning.',
        guestCapacity: '2-8 Guests',
        amenities: [
            { icon: 'snowflake', title: 'Full Time AC', description: 'Bedroom & Dining' },
            { icon: 'coffee', title: 'Premium Dining', description: 'Expanded menu options' },
            { icon: 'tv', title: 'Entertainment', description: 'LED TV & Music System' },
        ],
        stats: {
            totalBoats: 4,
            rating: 4.7,
        },
        heroImage: '/packages/premium.webp',
        testimonials: [],
        whatsappTemplate: 'Hi, I am interested in the Premium Collection houseboats.',
    },
    {
        id: 'cat-luxury',
        slug: 'luxury',
        title: 'Luxury Collection',
        tagline: 'The Ultimate Floating Palace',
        description: 'Top-tier houseboats with jacuzzi, butler service, and unparalleled opulence.',
        shortDescription: 'Five-star amenities floating on the backwaters.',
        guestCapacity: '2-10 Guests',
        amenities: [
            { icon: 'crown', title: 'Butler Service', description: 'Personalized attention' },
            { icon: 'hot-tub', title: 'Jacuzzi / Bathtub', description: 'Private relaxation' },
            { icon: 'palette', title: 'Designer Interiors', description: 'Modern aesthetic' },
        ],
        stats: {
            totalBoats: 3,
            rating: 4.9,
        },
        heroImage: '/packages/luxury.webp',
        testimonials: [],
        whatsappTemplate: 'Hi, I am interested in the Luxury Collection houseboats.',
    },
    {
        id: 'cat-honeymoon',
        slug: 'honeymoon',
        title: 'Honeymoon Special',
        tagline: 'Romantic Getaways',
        description: 'Private 1-bedroom boats designed for romance with flower decorations and candlelight dinners.',
        shortDescription: 'Intimate setting for couples.',
        guestCapacity: '2 Guests',
        amenities: [
            { icon: 'heart', title: 'Flower Decor', description: 'Welcome arrangement' },
            { icon: 'moon', title: 'Candlelight Dinner', description: 'Romantic evening' },
            { icon: 'cake', title: 'Honeymoon Cake', description: 'Special celebration' },
        ],
        stats: {
            totalBoats: 2,
            rating: 4.9,
        },
        heroImage: '/packages/honeymoon.webp',
        testimonials: [],
        whatsappTemplate: 'Hi, I am looking for a Honeymoon Houseboat package.',
    },
    {
        id: 'cat-shared',
        slug: 'shared',
        title: 'Shared Experiences',
        tagline: 'Social & Budget Friendly',
        description: 'Book a room on a larger boat and enjoy the backwaters with fellow travelers.',
        shortDescription: 'Private bedroom with shared common areas.',
        guestCapacity: '2 Guests',
        amenities: [
            { icon: 'users', title: 'Social Atmosphere', description: 'Meet other travelers' },
            { icon: 'wallet', title: 'Economical', description: 'Best value option' },
            { icon: 'bed', title: 'Private Room', description: 'En-suite bathroom' },
        ],
        stats: {
            totalBoats: 4,
            rating: 4.4,
        },
        heroImage: '/packages/budget.jpg',
        testimonials: [],
        whatsappTemplate: 'Hi, I am interested in Shared Houseboat options.',
    },
];

export const BOATS: Boat[] = [
    // Deluxe Boats
    {
        id: 'boat-d1',
        name: 'Classic Kettuvallam',
        slug: 'classic-kettuvallam',
        category_id: 'cat-deluxe',
        categorySlug: 'deluxe',
        status: 'active',
        bedrooms: 1,
        capacity_adults: 2,
        capacity_children: 1,
        has_ac: true,
        cruise_hours: 5,
        images: {
            hero: '/images/serene-waters.webp',
            exterior: '/images/serene-waters.jpg',
            interior: '/collection/interior.jpg',
            bedroom: '/collection/IMG-20250617-WA0019 (3).jpg'
        },
        tagline: 'Traditional elegance',
        description: 'A beautiful single bedroom houseboat perfect for couples looking for a budget-friendly yet authentic experience.',
        pricePerNight: 8500,
        features: ['AC (9PM-6AM)', 'Kerala Cuisine', 'Upper Deck'],
        amenities: ['TV', 'Music System', 'Fishing Rods'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },
    {
        id: 'boat-d2',
        name: 'River Melody',
        slug: 'river-melody',
        category_id: 'cat-deluxe',
        categorySlug: 'deluxe',
        status: 'active',
        bedrooms: 2,
        capacity_adults: 4,
        capacity_children: 2,
        has_ac: true,
        cruise_hours: 5,
        images: {
            hero: '/images/backwater-sunset.webp',
            exterior: '/images/backwater-sunset.webp',
            interior: '/collection/interior2.jpg',
            bedroom: '/collection/IMG-20250617-WA0018 (3).jpg'
        },
        tagline: 'Family favorite',
        description: 'Spacious 2-bedroom boat ideal for small families.',
        pricePerNight: 12000,
        features: ['AC (9PM-6AM)', 'Kerala Cuisine', 'Sundeck'],
        amenities: ['TV', 'Music System', 'Games'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },
    {
        id: 'boat-d3',
        name: 'Green Haven',
        slug: 'green-haven',
        category_id: 'cat-deluxe',
        categorySlug: 'deluxe',
        status: 'active',
        bedrooms: 3,
        capacity_adults: 6,
        capacity_children: 2,
        has_ac: true,
        cruise_hours: 5,
        images: {
            hero: '/images/palm-lined-canals.webp',
            exterior: '/images/palm-lined-canals.webp',
            interior: '/collection/chair.jpg',
            bedroom: '/collection/IMG-20250217-WA0123 (3).jpg'
        },
        tagline: 'Group getaway',
        description: 'Perfect for groups of friends, offering 3 cozy bedrooms.',
        pricePerNight: 16000,
        features: ['AC (9PM-6AM)', 'Kerala Cuisine', 'Open Lounge'],
        amenities: ['TV', 'Music System', 'Safety Jackets'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },

    // Premium Boats
    {
        id: 'boat-p1',
        name: 'Royal Heritage',
        slug: 'royal-heritage',
        category_id: 'cat-premium',
        categorySlug: 'premium',
        status: 'active',
        bedrooms: 2,
        capacity_adults: 4,
        capacity_children: 2,
        has_ac: true,
        cruise_hours: 6,
        images: {
            hero: '/images/premium-interiors.webp',
            exterior: '/collection/hero.jpg',
            interior: '/images/premium-interiors.webp',
            bedroom: '/collection/IMG-20250617-WA0019 (3).jpg'
        },
        tagline: 'Glass-walled luxury',
        description: 'Enjoy the view from your air-conditioned living area anytime.',
        pricePerNight: 18000,
        features: ['Full Time AC', 'Glass Windows', 'Premium Menu'],
        amenities: ['WiFi', 'Smart TV', 'Bluetooth Speaker'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },
    {
        id: 'boat-p2',
        name: 'Lake Prince',
        slug: 'lake-prince',
        category_id: 'cat-premium',
        categorySlug: 'premium',
        status: 'active',
        bedrooms: 3,
        capacity_adults: 6,
        capacity_children: 2,
        has_ac: true,
        cruise_hours: 6,
        images: {
            hero: '/images/onboard-dining.webp',
            exterior: '/images/onboard-dining.jpg',
            interior: '/collection/interior.jpg',
            bedroom: '/collection/IMG-20250617-WA0018 (3).jpg'
        },
        tagline: 'Exquisite dining',
        description: 'Known for its exceptional onboard dining experience and spacious interiors.',
        pricePerNight: 24000,
        features: ['Full Time AC', 'Premium Dining', 'Sundeck'],
        amenities: ['WiFi', 'Karaoke', 'Fishing Gear'],
        crew: { size: 4, roles: ['Captain', 'Chef', 'Helper', 'Guide'] }
    },
    {
        id: 'boat-p3',
        name: 'Azure Pearl',
        slug: 'azure-pearl',
        category_id: 'cat-premium',
        categorySlug: 'premium',
        status: 'active',
        bedrooms: 4,
        capacity_adults: 8,
        capacity_children: 4,
        has_ac: true,
        cruise_hours: 6,
        images: {
            hero: '/collection/IMG-20250617-WA0013 (3).jpg',
            exterior: '/collection/IMG-20250617-WA0013 (3).jpg',
            interior: '/collection/chair.jpg',
            bedroom: '/collection/IMG-20250217-WA0121 (3).jpg'
        },
        tagline: 'Large family retreat',
        description: 'A massive 4-bedroom premium boat for extended families.',
        pricePerNight: 32000,
        features: ['Full Time AC', 'Large Lounge', 'Premium Service'],
        amenities: ['WiFi', 'Home Theatre', 'Board Games'],
        crew: { size: 5, roles: ['Captain', 'Chef', '2 Helpers', 'Manager'] }
    },

    // Luxury Boats
    {
        id: 'boat-l1',
        name: 'The Vaikundam',
        slug: 'the-vaikundam',
        category_id: 'cat-luxury',
        categorySlug: 'luxury',
        status: 'active',
        bedrooms: 2,
        capacity_adults: 4,
        capacity_children: 0,
        has_ac: true,
        cruise_hours: 7,
        images: {
            hero: '/images/luxury-houseboat-exterior.webp',
            exterior: '/images/luxury-houseboat-exterior.webp',
            interior: '/images/premium-interiors.webp',
            bedroom: '/collection/IMG-20250617-WA0019 (3).jpg'
        },
        tagline: 'Floating palace',
        description: 'Experience royalty with jacuzzi, butler service and ultra-premium finishings.',
        pricePerNight: 45000,
        features: ['Central AC', 'Jacuzzi', 'Butler Service'],
        amenities: ['Starlink WiFi', 'Netflix', 'Minibar'],
        crew: { size: 4, roles: ['Captain', 'Executive Chef', 'Butler', 'Helper'] }
    },
    {
        id: 'boat-l2',
        name: 'Spice Coast Cruiser',
        slug: 'spice-coast-cruiser',
        category_id: 'cat-luxury',
        categorySlug: 'luxury',
        status: 'active',
        bedrooms: 1,
        capacity_adults: 2,
        capacity_children: 0,
        has_ac: true,
        cruise_hours: 7,
        images: {
            hero: '/collection/hero.jpg',
            exterior: '/collection/hero.jpg',
            interior: '/collection/interior2.jpg',
            bedroom: '/collection/IMG-20250217-WA0123 (3).jpg'
        },
        tagline: 'Intimate luxury',
        description: 'A single bedroom luxury craft for those who demand the best.',
        pricePerNight: 35000,
        features: ['Central AC', 'Private Deck', 'Gourmet Meals'],
        amenities: ['High-speed WiFi', 'Premium Sound', 'Bathtub'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Butler'] }
    },
    {
        id: 'boat-l3',
        name: 'Majestic Waters',
        slug: 'majestic-waters',
        category_id: 'cat-luxury',
        categorySlug: 'luxury',
        status: 'active',
        bedrooms: 3,
        capacity_adults: 6,
        capacity_children: 2,
        has_ac: true,
        cruise_hours: 7,
        images: {
            hero: '/images/hero.jpg',
            exterior: '/images/hero.jpg',
            interior: '/images/onboard-dining.webp',
            bedroom: '/collection/IMG-20250617-WA0018 (3).jpg'
        },
        tagline: 'Grandeur afloat',
        description: 'Three bedrooms of pure luxury, perfect for high-end corporate retreats or VIP families.',
        pricePerNight: 60000,
        features: ['Central AC', 'Conference Area', 'Full Service'],
        amenities: ['Video Conferencing', 'Bar Counter', 'Massage Chair'],
        crew: { size: 5, roles: ['Captain', 'Chef', 'Butler', '2 Helpers'] }
    },

    // Honeymoon
    {
        id: 'boat-h1',
        name: 'Cupid’s Arrow',
        slug: 'cupids-arrow',
        category_id: 'cat-honeymoon',
        categorySlug: 'honeymoon',
        status: 'active',
        bedrooms: 1,
        capacity_adults: 2,
        capacity_children: 0,
        has_ac: true,
        cruise_hours: 6,
        images: {
            hero: '/packages/honeymoon.webp',
            exterior: '/images/sunset.jpg',
            interior: '/collection/interior.jpg',
            bedroom: '/collection/IMG-20250617-WA0019 (3).jpg'
        },
        tagline: 'Pure romance',
        description: 'Special honeymoon suite with privacy and romantic ambiance.',
        pricePerNight: 15000,
        features: ['Flower Decor', 'Candlelight Dinner', 'AC Bedroom'],
        amenities: ['Privacy Screens', 'Bluetooth Speaker', 'Welcome Drink'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },
    {
        id: 'boat-h2',
        name: 'Love Birds',
        slug: 'love-birds',
        category_id: 'cat-honeymoon',
        categorySlug: 'honeymoon',
        status: 'active',
        bedrooms: 1,
        capacity_adults: 2,
        capacity_children: 0,
        has_ac: true,
        cruise_hours: 6,
        images: {
            hero: '/images/sunset.jpg',
            exterior: '/images/sunset.jpg',
            interior: '/collection/interior2.jpg',
            bedroom: '/collection/thumbnail.jpg'
        },
        tagline: 'Sunset romance',
        description: 'Designed for couples to enjoy the stunning Alleppey sunsets in privacy.',
        pricePerNight: 16000,
        features: ['Sunset Cruise', 'Cake', 'Flower Bed'],
        amenities: ['Music System', 'Private Dining', 'Couple Shoot'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },
    {
        id: 'boat-h3',
        name: 'Eternal Bliss',
        slug: 'eternal-bliss',
        category_id: 'cat-honeymoon',
        categorySlug: 'honeymoon',
        status: 'active',
        bedrooms: 1,
        capacity_adults: 2,
        capacity_children: 0,
        has_ac: true,
        cruise_hours: 6,
        images: {
            hero: '/collection/IMG-20250217-WA0121 (3).jpg',
            exterior: '/collection/IMG-20250217-WA0121 (3).jpg',
            interior: '/images/premium-interiors.webp',
            bedroom: '/collection/IMG-20250617-WA0013 (3).jpg'
        },
        tagline: 'Luxury honeymoon',
        description: 'A premium honeymoon boat with glass walls and full-time AC.',
        pricePerNight: 22000,
        features: ['Full Time AC', 'Jacuzzi', 'Special Menu'],
        amenities: ['Photography props', 'Smart TV', 'Fruit Basket'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] }
    },

    // Shared
    {
        id: 'boat-s1',
        name: 'Community Cruiser',
        slug: 'community-cruiser',
        category_id: 'cat-shared',
        categorySlug: 'shared',
        status: 'active',
        bedrooms: 5,
        capacity_adults: 10,
        capacity_children: 5,
        has_ac: true,
        cruise_hours: 5,
        images: {
            hero: '/packages/budget.jpg',
            exterior: '/packages/budget.jpg',
            interior: '/collection/chair.jpg',
            bedroom: '/collection/IMG-20250217-WA0123 (3).jpg'
        },
        tagline: 'Meet & Greet',
        description: 'A 5-bedroom boat where you book a single room. Great for meeting people.',
        pricePerNight: 5000,
        features: ['Private Room', 'Shared Dining', 'AC Bedroom'],
        amenities: ['Common TV', 'Card Games', 'Observation Deck'],
        crew: { size: 4, roles: ['Captain', 'Chef', '2 Helpers'] },
        price_override: 5000 // Per room
    },
    {
        id: 'boat-s2',
        name: 'Backwater Hostel',
        slug: 'backwater-hostel',
        category_id: 'cat-shared',
        categorySlug: 'shared',
        status: 'active',
        bedrooms: 4,
        capacity_adults: 8,
        capacity_children: 4,
        has_ac: true,
        cruise_hours: 5,
        images: {
            hero: '/collection/IMG-20250617-WA0018 (3).jpg',
            exterior: '/collection/IMG-20250617-WA0018 (3).jpg',
            interior: '/collection/interior.jpg',
            bedroom: '/collection/IMG-20250617-WA0019 (3).jpg'
        },
        tagline: 'Travelers choice',
        description: 'Economical way to enjoy the backwaters.',
        pricePerNight: 4500,
        features: ['Budget Friendly', 'Clean Rooms', 'Tasty Food'],
        amenities: ['WiFi', 'Charging Points', 'Lounge'],
        crew: { size: 3, roles: ['Captain', 'Chef', 'Helper'] },
        price_override: 4500
    },
    {
        id: 'boat-s3',
        name: 'Voyager Shared',
        slug: 'voyager-shared',
        category_id: 'cat-shared',
        categorySlug: 'shared',
        status: 'active',
        bedrooms: 6,
        capacity_adults: 12,
        capacity_children: 6,
        has_ac: true,
        cruise_hours: 5,
        images: {
            hero: '/images/serene-waters.jpg',
            exterior: '/images/serene-waters.jpg',
            interior: '/images/onboard-dining.jpg',
            bedroom: '/collection/thumbnail.jpg'
        },
        tagline: 'Large group shared',
        description: 'A massive 6-bedroom boat with private rooms available.',
        pricePerNight: 5500,
        features: ['Spacious', 'Sundeck Access', 'All Meals'],
        amenities: ['Music', 'Deck Chairs', 'Filtered Water'],
        crew: { size: 5, roles: ['Captain', 'Chef', '3 Helpers'] },
        price_override: 5500
    }
];
